### ISSUE TITLE
Liveries issue.

### ISSUE THREAD

**Issue by XxFri3ndlyxX** [lilfuchs/esx_lscustomsV2#11]
Not sure if anyone else has this issues but when i go to purchase livery it wont save. 
The thing is if i use other lscustom which use esx_menu  it will save. Can anybody help me with that. Please.

**Comment by OhTanoshi** [comment]
Im pretty sure thats a new update in esx should be simple to fix but i dont do any work on fivem anymore

**Comment by XxFri3ndlyxX** [comment]
It's all good i worked on this script and i'm improving it. I Forgot that i had open an issue. We can close it.
