### ISSUE TITLE
All mods are not showing for add-on vehicles

### ISSUE THREAD

**Issue by jakepavek** [lilfuchs/esx_lscustomsV2#5]

**Comment by OhTanoshi** [comment]
Ive tested multiple cars and im not 100% certain its this script as the only cars that had no mods also had no mods in vMenu even though they should have. ill do some more testing also to be sure. but a good ammount of my custom cars has body mods

**Comment by jakepavek** [comment]
I tried with the jeep rubicon and a few others and a few were working but not all of them. Tail light covers and read bumper. But grill and racks, front bumper etc did not show any

**Comment by OhTanoshi** [comment]
Ill look into it with a jeep but it seems like all is working just have wrong names etc

**Comment by OhTanoshi** [comment]
https://www.gta5-mods.com/vehicles/jeep-wrangler-2012-rubicon-v1-0 this jeeps car variations file is a little messed up. i found a fix you could do. 

`	  <Item>
          <modelName>jeep_bumperF_a</modelName>
          <modShopLabel>MNU_BUMR1</modShopLabel>
          <linkedModels />
          <turnOffBones>
            <Item>bumper_f</Item>
          </turnOffBones>
          <type>VMT_BUMPER_F</type>
          <bone>bumper_f</bone>
          <collisionBone>bumper_f</collisionBone>
          <cameraPos>VMCP_DEFAULT</cameraPos>
          <audioApply value="1.000000" />
          <weight value="0" />
          <turnOffExtra value="false" />
          <disableBonnetCamera value="false" />
          <allowBonnetSlide value="true" />
        </Item>`

**Comment by OhTanoshi** [comment]
Thats how i was able to fix the carcol on the jeep and allow for all customization for the front bumper

**Comment by OhTanoshi** [comment]
Best thing to do is to take say the slamvan3 carcol and remake the jeep inside of it. its A LOT of work but this lscustom's requires a properly set up carcols.meta im gonna work on making it more friendly with other ways but for now this is the only way

**Comment by OhTanoshi** [comment]
Another way is to use note pad++ and fix all BUMF1 and make it MNU_BUMF1

**Comment by OhTanoshi** [comment]
Only issue with addon cars is you will always have the wrong names for the bumpers and etc. im gonna look into making it just say custom bumper 1,2,3 etc but yeah.

**Comment by jakepavek** [comment]
I just did this

> `if lbl ~= nil then
					local mname = "Custom Part"
					-- if mname ~= "NULL" then
						local btn = m:addPurchase(mname,price)
						btn.modtype = mod
						btn.mod = i
						price = price + LSC_Config.prices.mods[mod].increaseby
					-- end
				end
			end		`

**Comment by OhTanoshi** [comment]
Where exactly did you add this? so i can put this in the update i'm about to push

**Comment by jakepavek** [comment]
i'll make a PR

**Comment by OhTanoshi** [comment]
Alright ill be waiting for it

**Comment by jakepavek** [comment]
its done

**Comment by OhTanoshi** [comment]
Awesome i tested and then merged.
