### ISSUE TITLE
error when translating

### ISSUE THREAD

**Issue by SanderAli** [lilfuchs/esx_lscustomsV2#9]
This script, is bestial but I think it has an error or it's me xD!

At the time of translating the sub-menu they are translated but you can not buy the pieces, and if you translate the menu, it remains in infinite loading screen, until fivem crash.

Do you know what the reason for this may be?

**Comment by OhTanoshi** [comment]
This is the first time someones brought this up, i can say for sure. I havent played or done anything on fivem since right about the last update on this happened but when i left it was working 100% with esx with no issues

**Comment by SanderAli** [comment]
It works fine, but for example, if you translate this:

LSCMenu.categories:addSubMenu("BUMPERS", "Bumpers", "Custom front and rear bumpers.",true)
to
LSCMenu.categories:addSubMenu("translate", "Bumpers", "translate",true)
still working but if you translate
LSCMenu.categories:addSubMenu("translate", "translate", "translate",true)
no longer works, it remains in infinite charge when trying to open the menu in the lscustom kinematics.

the 1st translates the title when you are inside the menu, the 2nd translates the menu

The rest works perfectly, it is one of the best custom ls I have seen, since it only loads the parts that the car has available to modify.

If you can help me with this, I would appreciate it, otherwise it is not a very serious problem.

Thanks again for sharing this resource.

**Comment by SanderAli** [comment]
In the end, it was a failure of its own.

I had to translate the mname, I had not noticed them.
